POST http://localhost:3001/api/blogs/5ddab8862b37ce1424c1e052/comments
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJYIiwiaWQiOiI1ZGRhNzJhY2ViMTYzNjEyYzAxNDRlZmMiLCJpYXQiOjE1NzQ1OTgzMjV9.l9W1Cb7z1cJ-yFp2gXzIjPrM9C5GMfzuUUgshsVvJug

{
  "text": "this is ALSO a comment...."
}